apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-homelab-routes
  namespace: traefik
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: homelab
  to:
    - group: gateway.networking.k8s.io
      kind: Gateway