apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service }}-anubis
  namespace: homelab
spec:
  selector:
    app: {{ .Values.service }}-anubis
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP