apiVersion: v2
name: transmission-flood
description: Flood UI with Transmission backend
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: anubis
    version: "*"
    repository: "file://../anubis"