deluge:
  env:
    TZ: "Europe/Amsterdam"

  persistence:
    config:
      enabled: true
      mountPath: /config
      type: pvc
      size: 1Gi
    downloads:
      enabled: true
      mountPath: /downloads
      type: pvc
      existingClaim: downloads