apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clamav
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sanderpeters/homelab
    targetRevision: main
    path: charts/clamav
    helm:
      dependencyUpdate: true

  destination:
    server: https://kubernetes.default.svc
    namespace: homelab

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
