apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: transmission-flood-route
  namespace: homelab
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik-gateway-controller
      sectionName: websecure
  hostnames:
    - "flood.sanderpeters.cloud"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: {{ .Release.Name }}-anubis
          port: 8080
          weight: 1