apiVersion: v2
name: anubis-observability
description: Observability stack for Anubis firewall
type: application
version: 0.1.0

dependencies:
  - name: kube-prometheus-stack
    version: "80.*"
    repository: https://prometheus-community.github.io/helm-charts