apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deluge-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging-issuer
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  tls:
    - hosts:
        - flood.sanderpeters.cloud
      secretName: deluge-tls
  rules:
    - host: flood.sanderpeters.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rflood
                port:
                  number: 3000