apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging-issuer
    traefik.ingress.kubernetes.io/redirect-to-https: "true"
    traefik.ingress.kubernetes.io/pass-client-ip: "true"
spec:
  tls:
    - hosts:
        - sanderpeters.cloud
      secretName: hello-world-tls
  rules:
    - host: sanderpeters.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-anubis
                port:
                  name: anubis