apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-tls
  namespace: traefik-gateway-controller
spec:
  secretName: gateway-tls
  issuerRef:
    name: letsencrypt-production-issuer
    kind: ClusterIssuer
  dnsNames:
    - sanderpeters.cloud
    - "*.sanderpeters.cloud"