[project]
name = "homelab"
version = "0.0.0"
description = "CLI for managing my homelab"
dependencies = [
    "cyclopts>=0.2.0",
    "plumbum>=1.10",
    "rich>=14.3.0"
]

[tool.setuptools]
packages = ["homelab"]

[project.scripts]
homelab = "homelab.cli:main"