apiVersion: v2
name: argocd-bootstrap
description: Bootstrap chart for Argo CD
type: application
version: 0.1.0
appVersion: "2.10.0"

dependencies:
  - name: argo-cd
    version: ^7.0.0
    repository: https://argoproj.github.io/argo-helm